nfc: uapi: use kernel size_t to fix user-space builds
stable inclusion
from stable-5.10.90
commit 818c9e0a04dff8fdec3ff70afcd25b945d8621d0
category: bugfix
issue: I5K2MH
CVE: NA

Signed-off-by: Fang Minjuan <fangminjuan5@huawei.com>
---------------------------------------

commit 79b69a83705e621b258ac6d8ae6d3bfdb4b930aa upstream.

Fix user-space builds if it includes /usr/include/linux/nfc.h before
some of other headers:

  /usr/include/linux/nfc.h:281:9: error: unknown type name ‘size_t’
    281 |         size_t service_name_len;
        |         ^~~~~~

Fixes: d646960f7986 ("NFC: Initial LLCP support")
Cc: <stable@vger.kernel.org>
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: fangminjuan <fangminjuan5@huawei.com>