kbuild: lto: add _mcount to list of used symbols
mainline inclusion
from mainline-5.12-rc1
commit da83616bcd3fa84233f6e37e2cf8cbfa979c6927
category: bugfix
issue: I5MXBS
CVE: NA

Signed-off-by: GUO Zihua <guozihua@huawei.com>
--------------------------------

Some randconfig builds fail with undefined references to _mcount
when CONFIG_TRIM_UNUSED_KSYMS is set:

ERROR: modpost: "_mcount" [drivers/tee/optee/optee.ko] undefined!
ERROR: modpost: "_mcount" [drivers/fsi/fsi-occ.ko] undefined!
ERROR: modpost: "_mcount" [drivers/fpga/dfl-pci.ko] undefined!

Since there is already a list of symbols that get generated at link
time, add this one as well.

Fixes: fbe078d397b4 ("kbuild: lto: add a default list of used symbols")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>