module: fix clang CFI with MODULE_UNLOAD=n
mainline inclusion
from mainline-5.15-rc6
commit 0d67e332e6df72f43eaa21228daa3a79e23093f3
category: bugfix
issue: I5MXBS
CVE: NA

Signed-off-by: GUO Zihua <guozihua@huawei.com>
--------------------------------

When CONFIG_MODULE_UNLOAD is disabled, the module->exit member
is not defined, causing a build failure:

kernel/module.c:4493:8: error: no member named 'exit' in 'struct module'
                mod->exit = *exit;

add an #ifdef block around this.

Fixes: cf68fffb66d6 ("add support for Clang CFI")
Acked-by: Kees Cook <keescook@chromium.org>
Reviewed-by: Sami Tolvanen <samitolvanen@google.com>
Reviewed-by: Miroslav Benes <mbenes@suse.cz>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Jessica Yu <jeyu@kernel.org>