fix build: declare ata_port_eh_scheduled() in libata.h
The deferred-qc backport calls ata_port_eh_scheduled() but never declares
it, causing:
  libata-scsi.c:1656: error: implicit declaration of function 'ata_port_eh_scheduled'

Signed-off-by: wanghao794 <wanghao865@huawei.com>