Bluetooth: hci_event: Fix coding style
stable inclusion
from stable-5.10.199
commit 7e83d15e0ca2fdad203df5f8a0d5b47dd083eb2e
category: bugfix
issue: #IA71TN
CVE: NA

Signed-off-by: wanxiaoqing <wanxiaoqing@huawei.com>
---------------------------------------

commit 35d91d95a0cd61ebb90e0246dc917fd25e519b8c upstream.

This fixes the following code style problem:

ERROR: that open brace { should be on the previous line
+       if (!bacmp(&hdev->bdaddr, &ev->bdaddr))
+       {

Fixes: 1ffc6f8cc332 ("Bluetooth: Reject connection with the device which has same BD_ADDR")
Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: wanxiaoqing <wanxiaoqing@huawei.com>