powerpc: Fix build error due to is_valid_bugaddr()
stable inclusion
from stable-5.10.210
commit 3928c06363de5c76cdeb527214f5ab720e739f5e
category: bugfix
issue: #IAJROA
CVE: NA

Signed-off-by: yaowenrui <yaowenrui2@huawei.com>
---------------------------------------

[ Upstream commit f8d3555355653848082c351fa90775214fb8a4fa ]

With CONFIG_GENERIC_BUG=n the build fails with:

  arch/powerpc/kernel/traps.c:1442:5: error: no previous prototype for ‘is_valid_bugaddr’ [-Werror=missing-prototypes]
  1442 | int is_valid_bugaddr(unsigned long addr)
       |     ^~~~~~~~~~~~~~~~

The prototype is only defined, and the function is only needed, when
CONFIG_GENERIC_BUG=y, so move the implementation under that.

Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://msgid.link/20231130114433.3053544-2-mpe@ellerman.id.au
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: yaowenrui <yaowenrui2@huawei.com>