kcsan: test: don't put the expect array on the stack
stable inclusion
from stable-5.10.166
commit 3b154d5204ff8aa82a2bd4d5ed29a7cf80723706
category: bugfix
issue: #I7T0NW
CVE: NA

Signed-off-by: huzhaodong <huzhaodong@huawei.com>
---------------------------------------

[ Upstream commit 5b24ac2dfd3eb3e36f794af3aa7f2828b19035bd ]

Size of the 'expect' array in the __report_matches is 1536 bytes, which
is exactly the default frame size warning limit of the xtensa
architecture.
As a result allmodconfig xtensa kernel builds with the gcc that does not
support the compiler plugins (which otherwise would push the said
warning limit to 2K) fail with the following message:

  kernel/kcsan/kcsan_test.c:257:1: error: the frame size of 1680 bytes
    is larger than 1536 bytes

Fix it by dynamically allocating the 'expect' array.

Signed-off-by: Max Filippov <jcmvbkbc@gmail.com>
Reviewed-by: Marco Elver <elver@google.com>
Tested-by: Marco Elver <elver@google.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: huzhaodong <huzhaodong@huawei.com>