crypto: arm64/gcm - Select AEAD for GHASH_ARM64_CE
stable inclusion
from stable-5.10.137
commit 64b1e3f90491177c81f86bed92f2053f29e41113
category: bugfix
issue: #I4UU4A
CVE: NA

Signed-off-by: lizongfeng <lizongfeng1@huawei.com>
---------------------------------------

[ Upstream commit fac76f2260893dde5aa05bb693b4c13e8ed0454b ]

Otherwise, we could fail to compile.

ld: arch/arm64/crypto/ghash-ce-glue.o: in function 'ghash_ce_mod_exit':
ghash-ce-glue.c:(.exit.text+0x24): undefined reference to 'crypto_unregister_aead'
ld: arch/arm64/crypto/ghash-ce-glue.o: in function 'ghash_ce_mod_init':
ghash-ce-glue.c:(.init.text+0x34): undefined reference to 'crypto_register_aead'

Fixes: 537c1445ab0b ("crypto: arm64/gcm - implement native driver using v8 Crypto Extensions")
Signed-off-by: Qian Cai <quic_qiancai@quicinc.com>
Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: lizongfeng <lizongfeng1@huawei.com>