netfilter: nftables: add nft_parse_register_load() and use it
stable inclusion
from stable-5.10.127
commit ec9b0a8d307ed0377699fe47bb4dc640e9184f8b
category: bugfix
issue: #I4UU4A
CVE: NA

Signed-off-by: gaochao <gaochao49@huawei.com>
---------------------------------------

[ Upstream commit 4f16d25c68ec844299a4df6ecbb0234eaf88a935 ]

This new function combines the netlink register attribute parser
and the load validation function.

This update requires to replace:

        enum nft_registers      sreg:8;

in many of the expression private areas otherwise compiler complains
with:

        error: cannot take address of bit-field ‘sreg’

when passing the register field as reference.

Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: gaochao <gaochao49@huawei.com>