hyperhold: fix undefined reference to `__aeabi_uldivmod` error
ohos inclusion
category: bugfix
issue: #I4T0KA
CVE: NA

-----------------
This patch fixes undefined reference to `__aeabi_uldivmod` error when
make allmodconfig on arm32. In a 32-bit system, if a or b is a 64-bit
value, you cannot simply use a/b, but need to use a special division
function, such as do_div(a, b), div_u64(a, b) and so on.

Signed-off-by: CY Fan <cy.fan@huawei.com>