Bluetooth: L2CAP: Fix l2cap_global_chan_by_psm regression
stable inclusion
from stable-5.10.137
commit c898e917d8bb317addcafa4511bde51af8e3976e
category: bugfix
issue: #I4UU4A
CVE: NA

Signed-off-by: lizongfeng <lizongfeng1@huawei.com>
---------------------------------------

commit 332f1795ca202489c665a75e62e18ff6284de077 upstream.

The patch d0be8347c623: "Bluetooth: L2CAP: Fix use-after-free caused
by l2cap_chan_put" from Jul 21, 2022, leads to the following Smatch
static checker warning:

        net/bluetooth/l2cap_core.c:1977 l2cap_global_chan_by_psm()
        error: we previously assumed 'c' could be null (see line 1996)

Fixes: d0be8347c623 ("Bluetooth: L2CAP: Fix use-after-free caused by l2cap_chan_put")
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: lizongfeng <lizongfeng1@huawei.com>