net: defxx: Fix missing err handling in dfx_init()
stable inclusion
from stable-5.10.163
commit 8ed99944572b118770253c81493a620673a0f96b
category: bugfix
issue: #I79BZA
CVE: NA

Signed-off-by: wanxiaoqing40281 <wanxiaoqing@huawei.com>
---------------------------------------

[ Upstream commit ae18dcdff0f8d7e84cd3fd9f496518b5e72d185d ]

When eisa_driver_register() or tc_register_driver() failed,
the modprobe defxx would fail with some err log as follows:

 Error: Driver 'defxx' is already registered, aborting...

Fix this issue by adding err hanling in dfx_init().

Fixes: e89a2cfb7d7b5 ("[TC] defxx: TURBOchannel support")
Signed-off-by: Yongqiang Liu <liuyongqiang13@huawei.com>
Reviewed-by: Jiri Pirko <jiri@nvidia.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: wanxiaoqing40281 <wanxiaoqing@huawei.com>